Refactor for scraped
everypolitician-scrapers/Alderney pull request #3
Opened 2017-01-26 11:54 UTC by ondenman

This is a step towards importing the new term. The next step will be to change the term id from 2014 to 2017.

2017-01-26 12:17 UTC, tmtmtmtm requested changes

2017-01-26 12:17 UTC, tmtmtmtm commented on scraper.rb
> +    data[:image] = URI.join(@BASE, URI.escape(data[:image])).to_s unless data[:image].to_s.empty?
Making the image absolute should happen in the class, not the consumer.

2017-01-26 12:17 UTC, tmtmtmtm commented on lib/members_page.rb
> +  field :members do
These aren't really `members`: these are just the URLs. This should either return more information on each one, or be renamed as just `member_urls`.

2017-01-27 10:37 UTC, tmtmtmtm requested changes

2017-01-27 10:37 UTC, tmtmtmtm commented on lib/member_page.rb
> +    URI.join(base, URI.escape(image)).to_s
Don't we have a Decorator to do this…?

2017-06-12 15:00 UTC, ondenman commented
Closing as the changes are now redundant.

2017-06-12 15:00 UTC, closed without merging