Refactor for scraped
everypolitician-scrapers/Alderney pull request #6
Opened 2017-02-15 13:07 UTC by ondenman

This is part of: https://github.com/everypolitician/everypolitician-data/issues/25302

The next step will be to add a decorator for the image paths. (Issue: https://github.com/everypolitician-scrapers/Alderney/issues/5)

2017-02-15 19:57 UTC, tmtmtmtm requested changes

2017-02-15 19:57 UTC, tmtmtmtm commented on test/member_page_test.rb
> +        image:  './media/image/6/o/140913_Alderney-801.jpg',
As before, you should really add a comment here (ideally with an issue number) to say that you know this is broken, and you're going to fix it RSN™

2017-02-15 19:57 UTC, tmtmtmtm commented on scraper.rb
> +scrape_list(2014, 'http://www.alderney.gov.gg/article/4077/States-Members')
There doesn't seem to be much value in having a separate `scrape_list` here any more, especially if you're changing its signature anyway

2017-02-15 19:57 UTC, tmtmtmtm commented on scraper.rb
> +    ScraperWiki.save_sqlite(%i(id term), data)
As discussed in Leeds, unless there's a good reason, let's aim for consistency by building up the `data` and then saving it in one shot.

2017-02-20 12:25 UTC, ondenman commented on test/member_page_test.rb
> +        image:  './media/image/6/o/140913_Alderney-801.jpg',
As a temporary fix, I've gone back to making the URL absolute in the MemberClass. The pre-factor data contains images with absolute URLs.

2017-02-22 11:41 UTC, tmtmtmtm approved these changes
:+1:

2017-02-23 09:18 UTC, merged